### ISSUE TITLE
initial specs

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/dialog#1]
A simple library to show alerts and confirmations
- use fidel
- use overlay
- escape button calls cancel function
- enter button calls ok function
- if cancelButton == false, don't show
- Options: 

```
title: ''
description: ''
okButton: 'OK'
cancelButton: 'Cancel'
okButtonClass: ''
cancelButtonClass: ''
ok: function() {}
cancel: function() {}
```

**Comment by Antonio-Laguna** [comment]
While developing this, I've encountered a weird bug within Fidel... It's hiding by itself the body. I'll try to find why is that happening.

**Comment by jgallen23** [comment]
any status on the bug?

**Comment by Antonio-Laguna** [comment]
The library is completed! I was expecting to talk to you today to see how can I do with tests since I'm facing some issues...
